### PR TITLE
Minor Admin Endpoint Changes

### PR DESCRIPTION
**Pull request by xenZero999**
- Does not show punishments or notes for anyone
- Shows all false booleans and does not show IPs for non-admins
- Shows IPs and accurate booleans for admins

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Is it really necessary to instantiate 3 new GSONBuilders with essentially the same settings in our if statements, whereas we can just have one final GSONBuilder, modify it in the if statements, and return that at the end? Or is that not how GSON works? 

Also, do we need to use .peek that much? Perhaps we may be able to use a function like filter, or collapse all of the repeated .peek calls into one?

**Comment by xenZero999** [comment]
> Is it really necessary to instantiate 3 new GSONBuilders with essentially the same settings in our if statements, whereas we can just have one final GSONBuilder, modify it in the if statements, and return that at the end? Or is that not how GSON works?

I am not entirely sure, but the original code does the same thing. That is definitely something worth looking into.

**Comment by Telesphoreo** [comment]
I feel like this whole thing could be done better for better code reusability. Instead of manually doing all of this in the HTTPD module, why not have more control at the source?
```java
        final PlexPlayer player = DataUtils.getPlayerByIP(ipAddress);
```
Why not have a boolean here that gives the option of loading extra data? So in this case the boolean would be false because we don't want to load all this extra data (punishments, notes). Maybe not loading extra data would only look like this
```json
[
  {
    "id": "f5cd54c4",
    "uuid": "f5cd54c4-3a24-4213-9a56-c06c49594dff",
    "name": "Taahh",
    "adminActive": false,
    "rank": "EXECUTIVE",
    "ips": [
      "X.X.X.X",
      "X.X.X.X"
    ]
  }
]
```

**Comment by Telesphoreo** [comment]
@allinkdev thoughts? since you assigned yourself this issue

**Comment by ghost** [comment]
> @allinkdev thoughts? since you assigned yourself this issue

I think, instead, if a user shouldn't be able to view the IPs and such of a player, the response's ips section shouldn't be shown at all.

e.g.

Non-admin request:
```json
[
  {
    "id": "f5cd54c4",
    "uuid": "f5cd54c4-3a24-4213-9a56-c06c49594dff",
    "name": "Taahh",
    "adminActive": false,
    "rank": "EXECUTIVE"
  }
]
```

Admin request:
```json
[
  {
    "id": "f5cd54c4",
    "uuid": "f5cd54c4-3a24-4213-9a56-c06c49594dff",
    "name": "Taahh",
    "adminActive": false,
    "rank": "EXECUTIVE",
    "ips": [
      "X.X.X.X",
      "X.X.X.X"
    ]
  }
]
```

**Comment by ghost** [comment]
> > Is it really necessary to instantiate 3 new GSONBuilders with essentially the same settings in our if statements, whereas we can just have one final GSONBuilder, modify it in the if statements, and return that at the end? Or is that not how GSON works?
> 
> I am not entirely sure, but the original code does the same thing. That is definitely something worth looking into.

Yeah, in all honesty, it shouldn't be doing that. It'd be best if you were to make the modified code not do the thing so we don't have to play around with merging commits

**Comment by Telesphoreo** [comment]
> > @allinkdev thoughts? since you assigned yourself this issue
> 
> I think, instead, if a user shouldn't be able to view the IPs and such of a player, the response's ips section shouldn't be shown at all.
> 
> e.g.
> 
> Non-admin request:
> 
> ```json
> [
>   {
>     "id": "f5cd54c4",
>     "uuid": "f5cd54c4-3a24-4213-9a56-c06c49594dff",
>     "name": "Taahh",
>     "adminActive": false,
>     "rank": "EXECUTIVE"
>   }
> ]
> ```
> 
> Admin request:
> 
> ```json
> [
>   {
>     "id": "f5cd54c4",
>     "uuid": "f5cd54c4-3a24-4213-9a56-c06c49594dff",
>     "name": "Taahh",
>     "adminActive": false,
>     "rank": "EXECUTIVE",
>     "ips": [
>       "X.X.X.X",
>       "X.X.X.X"
>     ]
>   }
> ]
> ```

The way it is done right now is that it reads the JSON and sets the list of "ips" to "" if the person viewing is not an admin. I believe we could hide it instead? I don't think we want to overcomplicate a `loadExtraData` boolean as this could be a debugging nightmare down the road. It should load the same data every time no matter what and then we can modify it accordingly on the HTTPD (obviously, different amount of data depending if the boolean is set to true or false)

**Comment by ghost** [comment]
Yeah, that's what I said.

**Comment by Telesphoreo** [comment]
> Yeah, that's what I said.

Ah sorry must have misunderstood

**Comment by ghost** [comment]
Hey there, I've decided to close this pull request because the system you've modified is due a rewrite and I'd think it would be harsh to ask you to do the entire rewrite for us. Thanks for the pull request though, as you've brought our attention to these issues. In place of this pull request, I've decided to open #8.

**Pull request closed without merging**
